# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
    - label: Home
      path: homepage
      class: first
    - label: About Us 
      path: about-us
      submenu:
          - label: Technical Teams
            path: about-us/technical-teams
          - label: Administrative Teams
            path: about-us/administrative-teams
          - label: Roster
            path: about-us/roster
    - label: cCar
      path: ccar
      submenu: 
          - label: Current cCar
            path: ccar
          - label: Past cCars
            path: ccar/past-ccars
    - label: eCar
      path: ecar
      submenu:
          - label: Current eCar
            path: ecar
          - label: Past eCars
            path: ecar/past-ecars
    - label: Competition
      path: competition
    - label: Sponsorship
      path: sponsorship
      submenu:
          - label: Current sponsors
            path: sponsorship/current-sponsors
          - label: Become a Sponsor
            path: sponsorship
    - label: Donate
      link: http://donate.uwformula.com
      class: external donate
    - label: Apply
      path: apply
    - label: Videos
      link: https://www.youtube.com/user/UWashingtonFSAE
      class: external youtube last
